[tools]
aichat = "latest"
codex = "0.117.0"
firebase = "15.16.0"
flutter = "latest"
gcloud = "latest"
gemini = "latest"
gemini-cli = "latest"
git-cliff = "latest"
go = "latest"
gradle = "latest"
java = "openjdk-17.0.2"
kotlin = "latest"
node = "22"
opencode = "latest"
pipx = "latest"
python = "3.12"
rust = "latest"
sqlite = "latest"
usage = "latest"
uv = "latest"
vercel = { version = "latest", allow_builds = ["esbuild"] }
wrangler = { version = "latest", allow_builds = ["esbuild", "sharp", "workerd"] }
yt-dlp = { version = "2026.03.17", rename_exe = "yt-dlp" }
