services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "${DK_POSTGRES}:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
