INPUTRC=$HOME/.config/readline/inputrc
CUDA_CACHE_PATH=$XDG_CACHE_HOME/nv
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/starship.toml
WGETRC=$XDG_CONFIG_HOME/wget/wgetrc
GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc
SHIV_ROOT=$XDG_CACHE_HOME/shiv
