# TPM
set -g @plugin 'tmux-plugins/tpm'

# Sensible defaults
set -g @plugin 'tmux-plugins/tmux-sensible'

# Navigation (vim integration)
set -g @plugin 'christoomey/vim-tmux-navigator'

# Clipboard
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TPM
run '~/.config/tmux/plugins/tpm/tpm'
